### ISSUE TITLE
GBA过亮色彩修复补丁

### ISSUE THREAD

**Issue by crashGG** [BSoD123456/ff5a_cn_fix#1]
FF5A针对GBA的屏幕做了过亮处理，这个色彩修复补丁，可以还原sfc的色彩，不过只针对欧版
https://www.romhacking.net/hacks/6841/

阁下能否把它移植到汉化版？

色彩修复+音色还原，FF5A 就算真的完善了。

**Comment by tringcooler** [comment]
这个补丁是给欧版用的，看起来并不适用日版（原汉化版使用的日版）。
因为原汉化版，以及现在的修正版，都对原日版ROM在文本以外的方面修改很少，
所以假如这个补丁真的能给日版使用，那么应该也能直接给汉化版使用。
这方面可以自行尝试。
